### ISSUE TITLE
Subclassing SWIGged classes is not working

### ISSUE THREAD

**Issue by spxiwh** [moble/GWFrames#49]
Hi Mike,

This is Ian Harry at AEI-Potsdam. One of our grad students (Roberto) was hitting a problem with GWFrames this morning after doing a fresh install with up-to-date code. Basically he saw:

```
In [1]: import GWFrames
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-1-7373719e1fc4> in <module>()
----> 1 import GWFrames

/Users/iwharry/Library/Python/2.7/lib/python/site-packages/GWFrames/__init__.py in <module>()
    151 # in `Waveforms.i`.
    152 
--> 153 class _MetaWaveform(type(_Waveform)):
    154     pass
    155 

TypeError: Error when calling the metaclass bases
    type 'SwigPyObjectType' is not an acceptable base type
```

Now this is a macbook, using macports, python 2.7, clang compiler, with everything up-to-date. Installing on our inhouse cluster does not produce any issues.

I poked around at this and saw that you are basically using this:

https://stackoverflow.com/questions/6469923/extending-swig-builtin-classes

to get around the fact the C++ classes are not subclassable when compiling with `-builtin`.  My suspicion is this "feature" was never intended to be there, and has been removed in the latest SWIG version. I reproduced this myself on my own macbook with SWIG Version 3.0.11.

Specifically, I suspect that this change in SWIG:

https://github.com/swig/swig/blob/master/CHANGES#L296

has broken this. I did try to figure out how to work around this, but I couldn't see any way other than having the C++ class be an attribute of a container class, which would not be easily backwards compatible. For now I suggested compiling without `-builtin` and this seems to work, but I suspect that we won't be the only people to run into this!

**Comment by moble** [comment]
Hi Ian!

This is related to [Vijay's comment](https://github.com/moble/GWFrames/issues/47#issuecomment-336276148) on issue #47, as well as swig/swig#808, and possibly even a bug in [python itself](https://github.com/swig/swig/issues/808#issuecomment-252535341).  The swig behavior was changed between swig versions 3.10 and 3.11.

I suppose removing `-builtin` should work, since that was actually the reason I had to do this subclassing thing to begin with.  Also, rolling back to an older swig might work.  But [Dan's comment](https://github.com/moble/GWFrames/issues/47#issue-44864629) suggests a very old swig might be needed.

But, as I mentioned on the other issue, this package isn't really supported any longer.  I haven't used it in several years, but I'm hoping to have all its functionality replaced soon.
