### ISSUE TITLE
Installing GWFrames in Python 3, Symbol not found: _Py_InitModule

### ISSUE THREAD

**Issue by eva-yhuang** [moble/GWFrames#53]
After I install GWFrames (I am using Swig 3.0.10) for python 3, then I encountered the following error message when `import GWFrames`
`
> 
> Traceback (most recent call last):
>   File "/Users/Evalien/miniconda3/pkgs/GWFrames/Code/GWFrames/__init__.py", line 19, in swig_import_helper
>     return importlib.import_module(mname)
>   File "/Users/Evalien/miniconda3/lib/python3.6/importlib/__init__.py", line 126, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 658, in _load_unlocked
>   File "<frozen importlib._bootstrap>", line 571, in module_from_spec
>   File "<frozen importlib._bootstrap_external>", line 922, in create_module
>   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
> ImportError: dlopen(/Users/Evalien/miniconda3/pkgs/GWFrames/Code/_GWFrames.cpython-36m-darwin.so, 2): Symbol not found: _Py_InitModule
>   Referenced from: /Users/Evalien/miniconda3/pkgs/GWFrames/Code/_GWFrames.cpython-36m-darwin.so
>   Expected in: flat namespace
>  in /Users/Evalien/miniconda3/pkgs/GWFrames/Code/_GWFrames.cpython-36m-darwin.so
>
> During handling of the above exception, another exception occurred:
>
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/Users/Evalien/miniconda3/pkgs/GWFrames/Code/GWFrames/__init__.py", line 22, in <module>
>     _GWFrames = swig_import_helper()
>   File "/Users/Evalien/miniconda3/pkgs/GWFrames/Code/GWFrames/__init__.py", line 21, in swig_import_helper
>     return importlib.import_module('_GWFrames')
>   File "/Users/Evalien/miniconda3/lib/python3.6/importlib/__init__.py", line 126, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
> ImportError: dlopen(/Users/Evalien/miniconda3/pkgs/GWFrames/Code/_GWFrames.cpython-36m-darwin.so, 2): Symbol not found: _Py_InitModule
>   Referenced from: /Users/Evalien/miniconda3/pkgs/GWFrames/Code/_GWFrames.cpython-36m-darwin.so
>   Expected in: flat namespace
>  in /Users/Evalien/miniconda3/pkgs/GWFrames/Code/_GWFrames.cpython-36m-darwin.so`

Any chance you guys know what the issue might be? I checked and I think I have all the dependencies up to date. Thanks a ton!

**Comment by moble** [comment]
I'm not exactly sure what's going on here, but it looks like you somehow have some component that was built for python 2, along with other components that were built for python 3.  In particular, `Py_InitModule` is a python 2 thing.  How, exactly, did you get GWFrames?  Did you build it yourself?

I should probably take this opportunity to point out that I'm not really supporting this package any more.  SWIG really went off the rails there about 5 years ago, and I just couldn't keep up.  I've moved much of this package's functionality (and more) into [the `scri` module](https://github.com/moble/scri), though the main missing feature is post-Newtonian waveforms.  Unless you need PN waveforms, you might want to look into scri instead.

@10220, since you have more experience getting this built and running lately, do you have any insight as to exactly which versions of everything will work?

**Comment by 10220** [comment]
Ah yes, I have not found a way to get GWFrames to work with Python 3. From my own experience, I've only gotten it to work by compiling it entirely with Python 2 (and SWIG 3.0.10).

**Comment by eva-yhuang** [comment]
Hi @moble @10220 Thanks a lot! I managed to build it and run with Python 2.7.
